### ISSUE TITLE
JAVA-PROYECTO PCMUNDO-Clase Orden

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/chacoDevsTeam-3Sem#18]
Se requiere  crear la clase Orden la cual debe contar con los siguientes atributos un arreglo de objetos Computadora, un id de orden, debe crearse un metdo mostrarOrden el cual debe mostrar el id de orden generado y el arreglo de computadoras. 
Tambien debe crearse un metodo agregarComputadora el cual debe tener como parametro  un objeto del tipo Computadora y este debe tener una validacion sobre el limite max del arreglo en caso de que exista lugar asigne una computadora a la orden

**Comment by Federico65744** [comment]
completado, esperando integración.
